### ISSUE TITLE
can you provide the way to get src_file in eval.py?

### ISSUE THREAD

**Issue by hugddygff** [seanie12/nqg#11]
Thanks.

**Comment by Brandonnogithub** [comment]
It's just the index . I generate it by myself. 1,2,3... n in each line. n is the number of samples

**Comment by hugddygff** [comment]
@Brandonnogithub Can you share the code? I get a unexpected high-score of BLEU.

**Comment by Brandonnogithub** [comment]
```
path = "src.txt"
n = 416  

f = open(path, "w")
for i in range(n):
    f.write(str(i)+"\n")
```
n is the size of test set. 
I get similar result in paper. 

Hope this can help you.

**Comment by hugddygff** [comment]
@Brandonnogithub Thanks, I have got the similar results.
