### ISSUE TITLE
How many times should we count for each context token in counter?

### ISSUE THREAD

**Issue by Stevring** [seanie12/nqg#13]
Hi seanie, thanks for your self-explanatory code. I have a question for the data preprocessing part (line 491~517 in `data_utils.py`):

    for qa in para["qas"]:
        total += 1
        ques = qa["question"].replace("''", '" ').replace("``", '" ').lower()
        ques_tokens = word_tokenize(ques)

        for token in ques_tokens:
        counter[token] += 1

        y1s, y2s = [], []
        answer_texts = []
    
        for answer in qa["answers"]:
              answer_text = answer["text"]
              answer_start = answer["answer_start"]
              answer_end = answer_start + len(answer_text)
              answer_texts.append(answer_text)
              answer_span = []

              for token in context_tokens:
                  counter[token] += len(para["qas"])

suppose we have one piece of context. The context has A questions, with B answers provided for each question. Then for each context token, it is counted by `A*B*A` times (`A*B` for the two `for` loops (line `408` and `509` separately), the last `A` for `len(para["qas"])` (line `517`) ).  

But I think each context token should be counted by only A times since every training example is a context-question-answer triple. In other words, each context token should be counted by the number of questions it has.

If I get something wrong, please correct it for me. Thanks in advance.

**Comment by seanie12** [comment]
@Stevring Yes I totally agree. The frequency of each token from one context should be counted A times
