### ISSUE TITLE
Does the Inference code work with "use_tag" as False

### ISSUE THREAD

**Issue by chunduri11** [seanie12/nqg#19]
My understanding of **use_tag** is that, the model does inference(generate questions) from the paragraph without answer.  Please correct me, if I am wrong.
But when I set use_tag as false, I get an error in the class 
`class SQuadDataset(data.Dataset):`

AssertionError: the number of source sequence 782600 and target sequence 5285 must be the same.

This happens as the assert statement expects the lengths to be same, but which  need not be the case. Looks like the code for this config settings is incomplete. 
@seanie12 It would great and very much helpful, if you can clarify my query. BTW... great work.

**Comment by seanie12** [comment]
1. The model generates a question q ~ p_{\theta}(q|c,a) where c,a, \theta is context, answer, and the parameter of the model. The model does not generate an answer from context, rather an answer is given to the model.  So you must feed an answer, which is an answer tag, to the model to generate an answer specific question. So if you don't feed an answer, the code will run without any error, but the quality of a question will degrade.

2. (c_i, a_i) should be paired with q_i to train model to generate a question that is relevant to the context and answer. So context with an answer should be one-to-one correspondence with question. That is the purpose of the "assertion".

**Comment by chunduri11** [comment]
@seanie12 thanks for the quick reply.
When I run the code with use_tag as False, it runs into an error message. I think the code that uses dataloader with out use_tag has some issues.
Since you are suggesting that the questions generated with **use_tag as False** are not good, since they are generated with out having Answer as the input in addition to the paragraph. I will not need the option of **use_tag as False**.
The code works well with use_tag as True and generated question are good for squad data set.
