### ISSUE TITLE
cant train..

### ISSUE THREAD

**Issue by zm379096736** [seanie12/nqg#22]
OS:window 10
run main.py, but it will automatically break and no any error message.
it is work in linux 
![image](https://user-images.githubusercontent.com/9376499/78877883-18e2a600-7a84-11ea-9b86-7edd110f1b48.png)

**Comment by zm379096736** [comment]
![image](https://user-images.githubusercontent.com/9376499/78878927-c4402a80-7a85-11ea-93ac-7f2b30e817d4.png)

**Comment by seanie12** [comment]
Sorry, I didn't test my code on windows. Please run the code in Linux.
