### ISSUE TITLE
Generate question in our own

### ISSUE THREAD

**Issue by minhson-kaist** [seanie12/nqg#24]
Hi,
Thanks for your great work. I have a question in terms of using your code.

How can I produce question generation in my own way? For example, I have my sentence S and an answer A, how can I use your code to generate a question that returns the answer A from S?

**Comment by seanie12** [comment]
I will update my repo to generate questions from custom dataset.

**Comment by minhson-kaist** [comment]
Thanks, I really appreciate that.
