### ISSUE TITLE
Why choose config.beam_size * 2 instead of config.beam_size？

### ISSUE THREAD

**Issue by cz3344** [seanie12/nqg#25]
`top_k_log_probs, top_k_ids \
                = torch.topk(log_probs, config.beam_size * 2, dim=-1)` 

Hi @seanie12, thank you for sharing your codes. I learned a lot from them. They are elegant and easy-reading.
I got one doubt @line 145-146 in infenrence.py.
Why you choose config.beam_size * 2 instead of config.beam_size？

Btw, the inference.py supports batch_size = 1 only, right?

**Comment by cz3344** [comment]
Hi @seanie12, could you help to confirm? Thx.

**Comment by seanie12** [comment]
Yes you are right. There is no reason to use 2* beam size. 
My code for beam search only supports for the batch size 1. If you want to use it with multiple examples, please see the hugging face repo. PretrainedModel class has a function generate() which supporte various types of decoding.
