### ISSUE TITLE
embedding in beamsearch

### ISSUE THREAD

**Issue by theDyingofLight** [seanie12/nqg#29]
Hi, I am wondering why there is no embedding layer loaded from GloVe which comes to random embedding layer when you beam search. I add the embedding layer from Glove and the result is much higher. Thank you very much.

**Comment by seanie12** [comment]
Hi, thanks for the pointing it out.
I think the pretrained word embedding matrix is saved in pytorch state_dict.
I will check it out.
BTW, what was the final bleu score when you add glove embedding?

**Comment by theDyingofLight** [comment]
> Hi, thanks for the pointing it out.
> I think the pretrained word embedding matrix is saved in pytorch state_dict.
> I will check it out.
> BTW, what was the final bleu score when you add glove embedding?

I am sorry that I do not consider the parameters from state_dict. I have checked that the results with or without loading embedding are the same. Thank you very much. I am sorry.
