### ISSUE TITLE
how to get good results

### ISSUE THREAD

**Issue by qjzhzw** [seanie12/nqg#3]
Good job! Your code is so clear that I like it.

Unfortunately, I followed your code and hyperparameters, but got poor results (e.g., 4-5 for BLEU-4).

I failed to install pytorch_scatter, so I replaced the code:
`out, _ = scatter_max(energy, ext_src_seq, out=out)`
—>
`out = out.scatter_(1, ext_src_seq, energy)`

I think the poor result is not only determined by it, there should be more other details.

Can you give me some suggestions how you get the results (e.g., 16.28 for BLEU-4) ? Thanks very much!

**Comment by seanie12** [comment]
@qjzhzw
Thanks for being interested in my repo.

I think the most import part for the performance(BLEU ) is  ([copy mechanism](https://arxiv.org/abs/1704.04368).

If you failed to install torch-scatter, maybe you should try scatter_add() like [this](https://github.com/atulkum/pointer_summarizer/blob/master/training_ptr_gen/model.py#L194)
