### ISSUE TITLE
TypeError: expected Byte (got Bool)

### ISSUE THREAD

**Issue by buptgxt** [seanie12/nqg#5]
i operate the main.py

load train data
epoch 1/20 :
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "main.py", line 9, in main
    trainer.train()
  File "/home/gxt2018/neural-question-generation-master/trainer.py", line 80, in train
    batch_loss = self.step(train_data)
  File "/home/gxt2018/neural-question-generation-master/trainer.py", line 110, in step
    enc_mask = torch.ByteTensor(src_seq == enc_zeros)
TypeError: expected Byte (got Bool)
what's the problem? i have get the prodessd data

**Comment by qjzhzw** [comment]
You need to update your pytorch version to 1.1

**Comment by buptgxt** [comment]
My pytorch version is 1.2

**Comment by zm379096736** [comment]
my pytorch version is 1.3, same error

**Comment by jemmryx** [comment]
anyone who solves this problem? I got same error

**Comment by qjzhzw** [comment]
You need to change your pytorch version to 1.1, even though your version is 1.2 or 1.3

**Comment by seanie12** [comment]
enc_mask =(src_seq==0).byte() would work

**Comment by zm379096736** [comment]
> enc_mask =(src_seq==0).byte() would work

thanks,It really works!
