### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by buptgxt** [seanie12/nqg#7]
Traceback (most recent call last):
  File "./eval.py", line 101, in <module>
    eval(args.out_file, args.src_file, args.tgt_file)
  File "./eval.py", line 72, in eval
    pair['prediction'] = output[idx]
IndexError: list index out of range

python2 eval.py --out_file ../result/pointer_maxout_ans/generated.txt --src_file ../squad/para-test.txt --tgt_file ../squad/tgt-test.txt
i can't find the src_file

**Comment by seanie12** [comment]
Did you preprocess SQuAD dataset as CoNLL format?
src_file is the pre-processed file of SQuAD dev-set

**Comment by hugddygff** [comment]
@buptgxt do you solve this problem?

**Comment by seanie12** [comment]
#11
