### ISSUE TITLE
why loss so high?

### ISSUE THREAD

**Issue by zm379096736** [seanie12/nqg#9]
epoch 20/20 :
1/1369 [>                   ] - ETA : 7m 21s - loss : 9070295040.0000
2/1369 [>                   ] - ETA : 8m 24s - loss : 4338394624.0000
3/1369 [>                   ] - ETA : 8m 29s - loss : 6674082304.0000
4/1369 [>                   ] - ETA : 8m 45s - loss : 2183406080.0000
5/1369 [>                   ] - ETA : 8m 24s - loss : 3891050752.0000
6/1369 [>                   ] - ETA : 8m 25s - loss : 4.1338
7/1369 [>                   ] - ETA : 8m 40s - loss : 4.0085
8/1369 [>                   ] - ETA : 8m 48s - loss : 4.0731
9/1369 [>                   ] - ETA : 8m 38s - loss : 3.6342
10/1369 [>                   ] - ETA : 8m 28s - loss : 3.9003
11/1369 [>                   ] - ETA : 8m 30s - loss : 4.3736
12/1369 [>                   ] - ETA : 8m 19s - loss : 4.5384
13/1369 [>                   ] - ETA : 8m 13s - loss : 4.4331
14/1369 [>                   ] - ETA : 8m 11s - loss : 4.2445
15/1369 [>                   ] - ETA : 8m 6s - loss : 4.0990
16/1369 [>                   ] - ETA : 8m 9s - loss : 4.2780
17/1369 [>                   ] - ETA : 8m 9s - loss : 4615384576.0000
18/1369 [>                   ] - ETA : 8m 6s - loss : 10479042560.0000
19/1369 [>                   ] - ETA : 8m 8s - loss : 4.2966
......
1364/1369 [===================>] - ETA : 1s - loss : 4.4662
1365/1369 [===================>] - ETA : 1s - loss : 14598540288.0000
1366/1369 [===================>] - ETA : 0s - loss : 17287233536.0000
1367/1369 [===================>] - ETA : 0s - loss : 15384614912.0000
1368/1369 [===================>] - ETA : 0s - loss : 15047878656.0000
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :1/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :2/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :3/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :4/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :5/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :6/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :7/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :8/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :9/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :10/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :11/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :12/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :13/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :14/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :15/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :16/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :17/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :18/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :19/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :20/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :21/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :22/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :23/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :24/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :25/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :26/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :27/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :28/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :29/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :30/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :31/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :32/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :33/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :34/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :35/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :36/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :37/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :38/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :39/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :40/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :41/42
1369/1369 [=====================] - ETA : 0s - loss : 27573528576.0000 => Evaluating :42/42
Epoch 20 took 7m 42s - final loss : 27573528576.0000 - val loss :22477019635.8095

**Comment by seanie12** [comment]
I guess the target label is somewhat corrupted, so maxout-pointer net points to wrong token in the passage. 
Did you preprocess the SQuAD dataset as in the README?

**Comment by zm379096736** [comment]
> I guess the target label is somewhat corrupted, so maxout-pointer net points to wrong token in the passage.
> Did you preprocess the SQuAD dataset as in the README?
Yes, I follow your prompts, I pre-process again, but it's no different, I will delete all and try again.

**Comment by zm379096736** [comment]
> I guess the target label is somewhat corrupted, so maxout-pointer net points to wrong token in the passage.
> Did you preprocess the SQuAD dataset as in the README?

Yes, I follow your prompts, I pre-process again, but it's no different, I will delete all and try again.

**Comment by zm379096736** [comment]
I re-downloaded repo and followed the steps to pre-process, but the problem still exists.
Here is the difference from the repo:
at config.py line 23 replace `max_len = 400 ` to `max_seq_len = 400`
at preprocess.py append 
`import sys
sys.path.append('..')
import config
from data_utils import make_embedding, make_vocab_from_squad, \
    process_file, make_conll_format, \
    make_vocab
sys.path.remove('..')`
at trainer.py line 110 replace ` enc_mask = torch.ByteTensor(src_seq == enc_zeros)` to `enc_mask = (src_seq==0).byte()`
at main.py append 
```
import warnings
warnings.filterwarnings("ignore")
```

**Comment by seanie12** [comment]
Still don't know what's wrong with the code. How about setting use_pointer = False in config.py?

**Comment by zm379096736** [comment]
> Still don't know what's wrong with the code. How about setting use_pointer = False in config.py?

If use_pointer = False, its normal.but how can i fix it？

**Comment by zm379096736** [comment]
> > Still don't know what's wrong with the code. How about setting use_pointer = False in config.py?
> 
> If use_pointer = False, its normal.but how can i fix it？

result:
what is the name of the university of new york ?
what is the name of the university of new york university ?
what is the name of the university of new york city ?
what is the name of the university of new york city ?
what is the name of the UNKNOWN museum ?
what is the name of the UNKNOWN museum ?
what is the name of the UNKNOWN museum ?
what is the name of the UNKNOWN museum ?
what is the name of the UNKNOWN museum ?
what is the name of the UNKNOWN UNKNOWN ?
what is the name of the UNKNOWN ?
what is the name of the UNKNOWN ?
what is the name of the UNKNOWN UNKNOWN ?
...
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is an example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?
what is a example of a UNKNOWN ?

**Comment by zm379096736** [comment]
Would you mind give me processed para-test.txt example?

**Comment by seanie12** [comment]
Sorry for the late replay. Unkown word is generated because the model didnt use copy mechanism if use_pointer = False.
Absolutely not.  I will send the file if you give me your  email address

**Comment by zm379096736** [comment]
mingzeng96@gmail.com, thanks a lot.

Seanie Lee <notifications@github.com>於 2019年11月14日 週四，下午7:55寫道：
